name: Sync with upstream

on:
  schedule:
    # - cron: '0 7 * * 1,4'
    - cron: "*/5 * * * *"
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:  # click the button on Github repo!
  push:

jobs:
  sync_master: # master follows upstream strictly
    runs-on: ubuntu-latest
    name: Sync master with upstream
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull (Fast-Forward) upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
        with:
          upstream_repository: Gibberlings3/iesdp
          upstream_branch: master
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

  sync_bgforge: # bgforge is a branch with cosmetic changes
    runs-on: ubuntu-latest
    name: Sync bgforge with upstream master
    steps:
      - name: Checkout bgforge
        uses: actions/checkout@v2
        with:
          ref: bgforge
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Pull (Fast-Forward) upstream changes (bgforge)
        id: sync-bgforge
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
        with:
          upstream_repository: Gibberlings3/iesdp
          upstream_branch: master
          target_branch: bgforge
          github_token: ${{ secrets.GITHUB_TOKEN }}
