name: Sync with upstream

on:
  schedule:
    - cron: '33 7 * * *'
  workflow_dispatch:  # click the button on Github repo!
  push:

jobs:
  sync_master: # master follows upstream strictly
    runs-on: ubuntu-latest
    name: Sync master with upstream
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.target_repo_token }}

      - name: Pull (Fast-Forward) upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: Gibberlings3/iesdp
          upstream_sync_branch: master
          upstream_pull_args: "--all"
          target_sync_branch: master
          target_repo_token: ${{ secrets.target_repo_token }}

  sync_bgforge: # bgforge is a branch with cosmetic changes
    runs-on: ubuntu-latest
    name: Sync bgforge with upstream master
    steps:
      - name: Checkout bgforge
        uses: actions/checkout@v3
        with:
          ref: bgforge
          token: ${{ secrets.target_repo_token }}
          fetch-depth: 0

      - name: Pull (Fast-Forward) upstream changes (bgforge)
        id: sync-bgforge
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: Gibberlings3/iesdp
          upstream_sync_branch: master
          upstream_pull_args: "--all"
          target_sync_branch: bgforge
          target_repo_token: ${{ secrets.target_repo_token }}

  sync_ielib: # ielib is a branch with data changes, necessary for import into BGforge MLS and IElib
    runs-on: ubuntu-latest
    name: Sync ielib with upstream master
    steps:
      - name: Checkout ielib
        uses: actions/checkout@v3
        with:
          ref: ielib
          token: ${{ secrets.target_repo_token }}
          fetch-depth: 0

      - name: Pull (Fast-Forward) upstream changes (ielib)
        id: sync-ielib
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: Gibberlings3/iesdp
          upstream_sync_branch: master
          upstream_pull_args: "--all"
          target_sync_branch: ielib
          target_repo_token: ${{ secrets.target_repo_token }}
