name: Updater

on:
  push:
    branches: [ master ]

jobs:
  build_zip:
    runs-on: ubuntu-latest

    # ensure the zip archive has proper links ... so manually trigger the build after some prep
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: Install deps
      run: gem install github-pages jekyll-liquify

    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Push to other branch for a clean build
      run: bash deploy.sh
