name: Updater

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    # ensure the zip archive has proper links ... so manually trigger the build after some prep
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Build site
      uses: limjh16/jekyll-action-ts@v2

    - name: Push cleaned up build to other branch
      run: bash deploy.sh
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
